scripts done, time to test

diff --git a/precise/mongodb-management-service/hooks/config-changed b/precise/mongodb-management-service/hooks/config-changed
--- a/precise/mongodb-management-service/hooks/config-changed
+++ b/precise/mongodb-management-service/hooks/config-changed
@@ -1,2 +1,15 @@
 #!/bin/bash
 # config-changed occurs everytime a new configuration value is updated (juju set)
+
+set -e
+
+. $CHARM_DIR/scripts/common-variables.sh
+
+MMS_API_KEY=$(config-get mms-api-key)
+if [ -z $MMS_API_KEY ]; then juju-log "missing MMS_API_KEY"; exit 666; fi
+
+MMS_SECRET_KEY=$(config-get mms-secret-key)
+if [ -z $MMS_SECRET_KEY ]; then juju-log "missing MMS_SECRET_KEY"; exit 666; fi
+
+sed -i.bak s/\@API_KEY\@/$MMS_API_KEY/ ${MMS_HOME}/settings.py
+sed -i.bak s/\@SECRET_KEY\@/$MMS_SECRET_KEY/ ${MMS_HOME}/settings.py
diff --git a/precise/mongodb-management-service/hooks/start b/precise/mongodb-management-service/hooks/start
--- a/precise/mongodb-management-service/hooks/start
+++ b/precise/mongodb-management-service/hooks/start
@@ -2,3 +2,14 @@
 # Here put anything that is needed to start the service.
 # Note that currently this is run directly after install
 # i.e. 'service apache2 start'
+
+set -e
+
+. $CHARM_DIR/scripts/common-variables.sh
+
+if [ -f /etc/init/${SVC_NAME}.conf ]; then
+ service "${SVC_NAME}" start
+else
+ juju-log "${SVC_NAME} not ready yet.  cannot start"
+fi
+
diff --git a/precise/mongodb-management-service/hooks/stop b/precise/mongodb-management-service/hooks/stop
--- a/precise/mongodb-management-service/hooks/stop
+++ b/precise/mongodb-management-service/hooks/stop
@@ -1,7 +1,16 @@
 #!/bin/bash
-# This will be run when the service is being torn down, allowing you to disable
-# it in various ways..
-# For example, if your web app uses a text file to signal to the load balancer
-# that it is live... you could remove it and sleep for a bit to allow the load
-# balancer to stop sending traffic.
-# rm /srv/webroot/server-live.txt && sleep 30
+# Here put anything that is needed to start the service.
+# Note that currently this is run directly after install
+# i.e. 'service apache2 start'
+
+set -e
+
+. $CHARM_DIR/scripts/common-variables.sh
+
+if [ -f /etc/init/${SVC_NAME}.conf ]; then
+ service "${SVC_NAME}" stop
+ rm /etc/init/${SVC_NAME}.conf
+else
+ juju-log "${SVC_NAME} not ready yet.  cannot stop"
+fi
+
